### PR TITLE
refactor: remove console log

### PR DESCRIPTION
**Pull request by marcusforsberg**
Hi Tim,

First of all, thanks for your awesome work on this component. I really hope this is merged into Radix at some point since we really need something like this. Regardless, this library will be of great help for my team going forward! 😊

This is just a tiny PR to remove a `console.log` statement I noticed may have been accidentally left in the code.

Thanks!

### CODE REVIEW

**Comment by timhettler** [comment]
Sounds great, @marcusforsberg! Message me here or in Discord if there's anything I can do to help.

**Comment by marcusforsberg** [comment]
@timhettler Hey Tim, any chance we can get a release pushed to npm with this fix? It seems minor but it's quite distracting to get it logged to the console all the time and I want to avoid having to publish this to our private registry. 😊

**Comment by timhettler** [comment]
Hello from the far future, @marcusforsberg! I finally released on update to  this package. `1.1.2` is the latest.

**Comment by marcusforsberg** [comment]
Awesome, thanks!

**Pull request merged**
